name: Published

on:
  push:
    branches:
      - master
jobs:
  pre-release-checks:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  publish-github-package-repo:
    needs: [pre-release-checks]
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 14.x with registry access
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --ignore-engines
      - name: Build
        run: yarn build
      - name: Publish to Github Package Repo
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run semantic-release
